-- KTX-MOBILE DATABASE SCHEMA (Supabase/Postgres)
-- Dựa trên cấu trúc hiện tại và mở rộng tương tự SmartNote

-- 1. Cài đặt ứng dụng
CREATE TABLE IF NOT EXISTS app_settings (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamp with time zone DEFAULT now()
);

-- 2. Tầng
CREATE TABLE IF NOT EXISTS floors (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    sort integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Phòng
CREATE TABLE IF NOT EXISTS rooms (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    floor_id uuid REFERENCES floors(id) ON DELETE CASCADE,
    code text NOT NULL,
    gender text,
    sort integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE rooms
    ADD COLUMN IF NOT EXISTS gender text;

-- 4. Người lao động (Công nhân/Sinh viên)
CREATE TABLE IF NOT EXISTS workers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_code text,
    full_name text NOT NULL,
    gender text,
    identity_number text,
    electricity_fee numeric DEFAULT 0,
    water_fee numeric DEFAULT 0,
    free_room_days integer DEFAULT 0,
    hometown text,
    phone text,
    dob date,
    recruiter text,
    note text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS employee_code text;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS gender text;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS identity_number text;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS electricity_fee numeric DEFAULT 0;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS water_fee numeric DEFAULT 0;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS free_room_days integer DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS workers_employee_code_unique
    ON workers (employee_code)
    WHERE employee_code IS NOT NULL;

-- 5. Lịch sử cư trú (Stays)
CREATE TABLE IF NOT EXISTS stays (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    worker_id uuid REFERENCES workers(id) ON DELETE CASCADE,
    room_id uuid REFERENCES rooms(id) ON DELETE CASCADE,
    date_in date NOT NULL,
    date_out date,
    electricity_start_reading numeric DEFAULT 0,
    water_start_reading numeric DEFAULT 0,
    electricity_end_reading numeric DEFAULT 0,
    water_end_reading numeric DEFAULT 0,
    electricity_amount numeric DEFAULT 0,
    water_amount numeric DEFAULT 0,
    total_amount numeric DEFAULT 0,
    utility_paid_at timestamp with time zone,
    utility_paid_month text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS electricity_start_reading numeric DEFAULT 0;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS water_start_reading numeric DEFAULT 0;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS electricity_end_reading numeric DEFAULT 0;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS water_end_reading numeric DEFAULT 0;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS electricity_amount numeric DEFAULT 0;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS water_amount numeric DEFAULT 0;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS total_amount numeric DEFAULT 0;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS utility_paid_at timestamp with time zone;

ALTER TABLE stays
    ADD COLUMN IF NOT EXISTS utility_paid_month text;

CREATE UNIQUE INDEX IF NOT EXISTS stays_one_active_per_worker
    ON stays (worker_id)
    WHERE date_out IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS rooms_unique_floor_code
    ON rooms (floor_id, code);

-- 6. Ghi chỉ số điện (Electricities)
CREATE TABLE IF NOT EXISTS electricities (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id uuid REFERENCES rooms(id) ON DELETE CASCADE,
    month date NOT NULL, -- Ngày đầu tháng (VD: 2026-04-01)
    start_reading numeric DEFAULT 0,
    end_reading numeric DEFAULT 0,
    readings jsonb DEFAULT '[]'::jsonb,
    paid boolean DEFAULT false,
    paid_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- 7. Ghi chỉ số nước (Water Records - Mở rộng)
CREATE TABLE IF NOT EXISTS water_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id uuid REFERENCES rooms(id) ON DELETE CASCADE,
    month date NOT NULL,
    start_reading numeric DEFAULT 0,
    end_reading numeric DEFAULT 0,
    readings jsonb DEFAULT '[]'::jsonb,
    paid boolean DEFAULT false,
    paid_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE electricities
    ADD COLUMN IF NOT EXISTS readings jsonb DEFAULT '[]'::jsonb;

ALTER TABLE water_records
    ADD COLUMN IF NOT EXISTS readings jsonb DEFAULT '[]'::jsonb;

-- 8. Thanh toán tổng hợp (Payments - Mở rộng)
CREATE TABLE IF NOT EXISTS payments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id uuid REFERENCES rooms(id) ON DELETE CASCADE,
    worker_id uuid REFERENCES workers(id),
    amount numeric NOT NULL,
    type text, -- 'rent', 'electricity', 'water', 'deposit'
    payment_method text, -- 'cash', 'transfer'
    note text,
    created_at timestamp with time zone DEFAULT now()
);

-- 9. Ghi chú chung (Notes - Tương tự SmartNote)
CREATE TABLE IF NOT EXISTS general_notes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    target_id uuid, -- Có thể là room_id hoặc worker_id
    target_type text, -- 'room', 'worker', 'global'
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);
