export const DEFAULT_SETTINGS = {
  siteName: "KTX",
  logoUrl: "/logo.png",
  roomGridCols: 3,
  canDeleteStructure: false,
  requirePasswordOnDelete: true,
  electricityPrice: 0,
  waterPrice: 0,
  waterBillingMode: "shared",
  roomMonthlyPrice: 0,
  roomBillingMode: "postpaid",
  defaultRoomCapacity: 8,
  roomCapacityById: {},
  billingMonth: "",
  billingCloseDay: 10,
  adminContact: {
    name: "",
    phone: "",
    email: "",
    zalo: "",
    note: "",
  },
  about: {
    companyName: "Ký túc xá",
    address: "",
    hotline: "0343.751.753",
    email: "",
    website: "",
    mapUrl: "",
    workingHours: "",
    services: [],
    rules: "",
    bankInfo: "",
    description: "",
    adminNotice: "",
  },
};
